/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        fontFamily: {
          sans: ['var(--font-body)'],
          body: ['var(--font-body)'],
          heading: ['var(--font-heading)'],
          display: ['var(--font-heading)'],
          serif: ['var(--font-heading)'],
        },
        transitionDuration: {
          '250': '250ms',
          '400': '400ms',
          '600': '600ms',
          '800': '800ms',
        },
        animation: {
          'orb-idle': 'orb-idle 4s ease-in-out infinite',
          'orb-listening': 'orb-listening 1.2s ease-in-out infinite',
          'orb-thinking': 'orb-thinking 3s linear infinite',
          'orb-speaking': 'orb-speaking 3s ease-in-out infinite',
          'ripple-1': 'ripple-ring 2s ease-out infinite',
          'ripple-2': 'ripple-ring 2s ease-out infinite 0.6s',
          'ripple-3': 'ripple-ring 2s ease-out infinite 1.2s',
          'sound-bar': 'sound-bar 0.6s ease-in-out infinite alternate',
          'speak-dot': 'speak-dot 1.2s ease-in-out infinite',
          'fade-in': 'fade-in 0.3s ease-out forwards',
        },
        keyframes: {
          'orb-idle': {
            '0%, 100%': { transform: 'scale(1)' },
            '50%': { transform: 'scale(1.04)' },
          },
          'orb-listening': {
            '0%, 100%': { transform: 'scale(1)' },
            '50%': { transform: 'scale(1.12)' },
          },
          'orb-thinking': {
            '0%': { transform: 'scale(1) rotate(0deg)' },
            '50%': { transform: 'scale(1.06) rotate(180deg)' },
            '100%': { transform: 'scale(1) rotate(360deg)' },
          },
          'orb-speaking': {
            '0%': { transform: 'scale(1)', borderRadius: '50%' },
            '25%': { transform: 'scale(1.06)', borderRadius: '48% 52% 50% 50%' },
            '50%': { transform: 'scale(1.03)', borderRadius: '50% 48% 52% 50%' },
            '75%': { transform: 'scale(1.08)', borderRadius: '50% 50% 48% 52%' },
            '100%': { transform: 'scale(1)', borderRadius: '50%' },
          },
          'ripple-ring': {
            '0%': { transform: 'scale(1)', opacity: '0.5' },
            '100%': { transform: 'scale(2.4)', opacity: '0' },
          },
          'sound-bar': {
            '0%': { height: '6px' },
            '100%': { height: '28px' },
          },
          'speak-dot': {
            '0%, 100%': { transform: 'scale(1)', opacity: '0.6' },
            '50%': { transform: 'scale(1.5)', opacity: '1' },
          },
          'fade-in': {
            '0%': { opacity: '0', transform: 'translateY(6px)' },
            '100%': { opacity: '1', transform: 'translateY(0)' },
          },
        },
        colors: {
          background: {
            50: 'oklch(var(--background-50) / <alpha-value>)',
            100: 'oklch(var(--background-100) / <alpha-value>)',
            200: 'oklch(var(--background-200) / <alpha-value>)',
            300: 'oklch(var(--background-300) / <alpha-value>)',
            400: 'oklch(var(--background-400) / <alpha-value>)',
            500: 'oklch(var(--background-500) / <alpha-value>)',
            600: 'oklch(var(--background-600) / <alpha-value>)',
            700: 'oklch(var(--background-700) / <alpha-value>)',
            800: 'oklch(var(--background-800) / <alpha-value>)',
            900: 'oklch(var(--background-900) / <alpha-value>)',
            950: 'oklch(var(--background-950) / <alpha-value>)',
          },
          primary: {
            50: 'oklch(var(--primary-50) / <alpha-value>)',
            100: 'oklch(var(--primary-100) / <alpha-value>)',
            200: 'oklch(var(--primary-200) / <alpha-value>)',
            300: 'oklch(var(--primary-300) / <alpha-value>)',
            400: 'oklch(var(--primary-400) / <alpha-value>)',
            500: 'oklch(var(--primary-500) / <alpha-value>)',
            600: 'oklch(var(--primary-600) / <alpha-value>)',
            700: 'oklch(var(--primary-700) / <alpha-value>)',
            800: 'oklch(var(--primary-800) / <alpha-value>)',
            900: 'oklch(var(--primary-900) / <alpha-value>)',
            950: 'oklch(var(--primary-950) / <alpha-value>)',
          },
          accent: {
            50: 'oklch(var(--accent-50) / <alpha-value>)',
            100: 'oklch(var(--accent-100) / <alpha-value>)',
            200: 'oklch(var(--accent-200) / <alpha-value>)',
            300: 'oklch(var(--accent-300) / <alpha-value>)',
            400: 'oklch(var(--accent-400) / <alpha-value>)',
            500: 'oklch(var(--accent-500) / <alpha-value>)',
            600: 'oklch(var(--accent-600) / <alpha-value>)',
            700: 'oklch(var(--accent-700) / <alpha-value>)',
            800: 'oklch(var(--accent-800) / <alpha-value>)',
            900: 'oklch(var(--accent-900) / <alpha-value>)',
            950: 'oklch(var(--accent-950) / <alpha-value>)',
          },
          secondary: {
            50: 'oklch(var(--secondary-50) / <alpha-value>)',
            100: 'oklch(var(--secondary-100) / <alpha-value>)',
            200: 'oklch(var(--secondary-200) / <alpha-value>)',
            300: 'oklch(var(--secondary-300) / <alpha-value>)',
            400: 'oklch(var(--secondary-400) / <alpha-value>)',
            500: 'oklch(var(--secondary-500) / <alpha-value>)',
            600: 'oklch(var(--secondary-600) / <alpha-value>)',
            700: 'oklch(var(--secondary-700) / <alpha-value>)',
            800: 'oklch(var(--secondary-800) / <alpha-value>)',
            900: 'oklch(var(--secondary-900) / <alpha-value>)',
            950: 'oklch(var(--secondary-950) / <alpha-value>)',
          },
          foreground: {
            50: 'oklch(var(--foreground-50) / <alpha-value>)',
            100: 'oklch(var(--foreground-100) / <alpha-value>)',
            200: 'oklch(var(--foreground-200) / <alpha-value>)',
            300: 'oklch(var(--foreground-300) / <alpha-value>)',
            400: 'oklch(var(--foreground-400) / <alpha-value>)',
            500: 'oklch(var(--foreground-500) / <alpha-value>)',
            600: 'oklch(var(--foreground-600) / <alpha-value>)',
            700: 'oklch(var(--foreground-700) / <alpha-value>)',
            800: 'oklch(var(--foreground-800) / <alpha-value>)',
            900: 'oklch(var(--foreground-900) / <alpha-value>)',
            950: 'oklch(var(--foreground-950) / <alpha-value>)',
          },
        },
      },
    },
    plugins: [],
  }